/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'outline-variant': '#c4c6cf',
        'tertiary-fixed-dim': '#76d6d5',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1a1c1c',
        'on-error': '#ffffff',
        'tertiary-container': '#002323',
        'surface-container-highest': '#e2e2e2',
        'primary-fixed': '#d4e3ff',
        background: '#f9f9f9',
        primary: '#000613',
        'on-secondary-container': '#745c00',
        'on-tertiary-container': '#2c9494',
        'primary-container': '#001f3f',
        'surface-tint': '#476083',
        'primary-fixed-dim': '#afc8f0',
        'surface-variant': '#e2e2e2',
        tertiary: '#000707',
        'inverse-surface': '#2f3131',
        'secondary-container': '#fed65b',
        'on-tertiary-fixed': '#002020',
        'surface-container-high': '#e8e8e8',
        'on-secondary-fixed': '#241a00',
        'tertiary-fixed': '#93f2f2',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'on-background': '#1a1c1c',
        'on-secondary-fixed-variant': '#574500',
        'surface-dim': '#dadada',
        'inverse-primary': '#afc8f0',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'surface-bright': '#f9f9f9',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'surface-container': '#eeeeee',
        'secondary-fixed-dim': '#e9c349',
        'on-tertiary-fixed-variant': '#004f4f',
        'surface-container-low': '#f3f3f3',
        outline: '#74777f',
        surface: '#f9f9f9',
        'on-surface-variant': '#43474e',
        'on-primary-container': '#6f88ad',
        'on-primary-fixed-variant': '#2f486a',
        'secondary-fixed': '#ffe088',
        'on-primary-fixed': '#001c3a',
        secondary: '#735c00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-padding': '80px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        gutter: '24px',
        base: '8px',
      },
      fontFamily: {
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
