/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        white: '#ffffff',

        // Ink (near-black)
        primary: '#131c15',
        'on-primary': '#ffffff',
        'primary-container': '#1c2620',
        'on-primary-container': '#a9b3ad',
        'primary-fixed': '#e3e8e5',
        'primary-fixed-dim': '#c5ccc8',
        'on-primary-fixed': '#131c15',
        'on-primary-fixed-variant': '#2c372f',
        'surface-tint': '#2c372f',
        'inverse-primary': '#a9eaf7',
        ink: '#131c15',
        'ink-soft': '#1c2620',

        // Aqua accent
        aqua: '#a9eaf7',
        'aqua-soft': '#d9f5fb',
        'aqua-deep': '#7fd6e8',
        secondary: '#131c15',
        'on-secondary': '#ffffff',
        'secondary-container': '#a9eaf7',
        'on-secondary-container': '#131c15',
        'secondary-fixed': '#a9eaf7',
        'secondary-fixed-dim': '#7fd6e8',
        'on-secondary-fixed': '#131c15',
        'on-secondary-fixed-variant': '#2c372f',

        tertiary: '#131c15',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d9f5fb',
        'on-tertiary-container': '#131c15',
        'tertiary-fixed': '#d9f5fb',
        'tertiary-fixed-dim': '#a9eaf7',
        'on-tertiary-fixed': '#131c15',
        'on-tertiary-fixed-variant': '#2c372f',

        // Panels are white, the page canvas is light grey
        canvas: '#f4f5f7',
        background: '#ffffff',
        surface: '#ffffff',
        'surface-bright': '#ffffff',
        'surface-dim': '#d9dde2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f5f7',
        'surface-container': '#eef0f3',
        'surface-container-high': '#e7eaee',
        'surface-container-highest': '#dfe3e8',
        'surface-variant': '#dfe3e8',
        'on-surface': '#131c15',
        'on-background': '#131c15',
        'on-surface-variant': '#4f5852',
        'inverse-surface': '#131c15',
        'inverse-on-surface': '#f4f5f7',
        outline: '#9aa19c',
        'outline-variant': '#e3e6ea',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      boxShadow: {
        sm: '0 1px 2px rgb(19 28 21 / 0.04)',
        DEFAULT: '0 2px 6px rgb(19 28 21 / 0.05)',
        md: '0 6px 16px -6px rgb(19 28 21 / 0.08)',
        lg: '0 12px 28px -10px rgb(19 28 21 / 0.1)',
        xl: '0 20px 40px -16px rgb(19 28 21 / 0.12)',
        '2xl': '0 30px 60px -20px rgb(19 28 21 / 0.18)',
        header: '0 10px 30px -12px rgb(19 28 21 / 0.18)',
        aqua: '0 16px 40px -14px rgb(127 214 232 / 0.65)',
      },
      transitionTimingFunction: {
        'out-soft': 'cubic-bezier(.22, 1, .36, 1)',
        line: 'cubic-bezier(.65, 0, .35, 1)',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.5rem',
        xl: '0.625rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'section-padding': '80px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        gutter: '24px',
        base: '8px',
      },
      fontFamily: {
        'headline-sm': ['Inter Tight', 'Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter Tight', 'Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter Tight', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['50px', { lineHeight: '56px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
