version: '0.1'

services:
  frontend:
    image: nginx:latest
    container_name: dt_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped
    
  backend:
    build: ./backend
    container_name: dt_backend
    environment:
      - DATABASE_URL="postgres://dt:dentaltourism@db:5432/dt?sslmode=disable"
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: unless-stopped

  db:
    build: ./db
    container_name: dental_tourism_db
    environment:
      POSTGRES_USER: dt
      POSTGRES_PASSWORD: dentaltourism
      POSTGRES_DB: dt
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dt_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports: 
      - 8888:80
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data: