// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsultation = `-- name: CreateConsultation :one
INSERT INTO consultations (
    patient_id,
    treatment_id,
    full_name,
    email,
    phone,
    country,
    city,
    message,
    panoramic_xray_url,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    COALESCE($10, 'new')
)
RETURNING
    id,
    patient_id,
    treatment_id,
    full_name,
    email,
    phone,
    country,
    city,
    message,
    panoramic_xray_url,
    status,
    created_at,
    updated_at
`

type CreateConsultationParams struct {
	PatientID        pgtype.UUID `json:"patient_id"`
	TreatmentID      pgtype.UUID `json:"treatment_id"`
	FullName         string      `json:"full_name"`
	Email            string      `json:"email"`
	Phone            string      `json:"phone"`
	Country          pgtype.Text `json:"country"`
	City             pgtype.Text `json:"city"`
	Message          pgtype.Text `json:"message"`
	PanoramicXrayUrl pgtype.Text `json:"panoramic_xray_url"`
	Status           interface{} `json:"status"`
}

func (q *Queries) CreateConsultation(ctx context.Context, arg CreateConsultationParams) (Consultation, error) {
	row := q.db.QueryRow(ctx, createConsultation,
		arg.PatientID,
		arg.TreatmentID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.City,
		arg.Message,
		arg.PanoramicXrayUrl,
		arg.Status,
	)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.TreatmentID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.Message,
		&i.PanoramicXrayUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConsultationsByStatus = `-- name: ListConsultationsByStatus :many
SELECT
    id,
    patient_id,
    treatment_id,
    full_name,
    email,
    phone,
    country,
    city,
    message,
    panoramic_xray_url,
    status,
    created_at,
    updated_at
FROM consultations
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConsultationsByStatus(ctx context.Context, status string) ([]Consultation, error) {
	rows, err := q.db.Query(ctx, listConsultationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.TreatmentID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.City,
			&i.Message,
			&i.PanoramicXrayUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsultationStatus = `-- name: UpdateConsultationStatus :one
UPDATE consultations
SET status = $2
WHERE id = $1
RETURNING
    id,
    patient_id,
    treatment_id,
    full_name,
    email,
    phone,
    country,
    city,
    message,
    panoramic_xray_url,
    status,
    created_at,
    updated_at
`

type UpdateConsultationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (Consultation, error) {
	row := q.db.QueryRow(ctx, updateConsultationStatus, arg.ID, arg.Status)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.TreatmentID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.Message,
		&i.PanoramicXrayUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
