// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Consultation struct {
	ID               uuid.UUID          `json:"id"`
	PatientID        pgtype.UUID        `json:"patient_id"`
	TreatmentID      pgtype.UUID        `json:"treatment_id"`
	FullName         string             `json:"full_name"`
	Email            string             `json:"email"`
	Phone            string             `json:"phone"`
	Country          pgtype.Text        `json:"country"`
	City             pgtype.Text        `json:"city"`
	Message          pgtype.Text        `json:"message"`
	PanoramicXrayUrl pgtype.Text        `json:"panoramic_xray_url"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Patient struct {
	ID        uuid.UUID          `json:"id"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
	Phone     string             `json:"phone"`
	Country   pgtype.Text        `json:"country"`
	City      pgtype.Text        `json:"city"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Testimonial struct {
	ID             uuid.UUID          `json:"id"`
	PatientID      pgtype.UUID        `json:"patient_id"`
	TreatmentID    pgtype.UUID        `json:"treatment_id"`
	PatientName    pgtype.Text        `json:"patient_name"`
	Rating         int32              `json:"rating"`
	CommentEn      pgtype.Text        `json:"comment_en"`
	PatientFlag    pgtype.Text        `json:"patient_flag"`
	DaysAgo        pgtype.Int4        `json:"days_ago"`
	ConsentGiven   bool               `json:"consent_given"`
	ConsentGivenAt pgtype.Timestamptz `json:"consent_given_at"`
	Anonymized     bool               `json:"anonymized"`
	Featured       bool               `json:"featured"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
