// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT
    id,
    full_name,
    email,
    phone,
    country,
    city,
    created_at,
    updated_at
FROM patients
WHERE email = $1
`

func (q *Queries) GetPatientByEmail(ctx context.Context, email string) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByEmail, email)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT
    id,
    full_name,
    email,
    phone,
    country,
    city,
    created_at,
    updated_at
FROM patients
WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPatientByEmail = `-- name: UpsertPatientByEmail :one
INSERT INTO patients (
    full_name,
    email,
    phone,
    country,
    city
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (email) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    country = EXCLUDED.country,
    city = EXCLUDED.city
RETURNING
    id,
    full_name,
    email,
    phone,
    country,
    city,
    created_at,
    updated_at
`

type UpsertPatientByEmailParams struct {
	FullName string      `json:"full_name"`
	Email    string      `json:"email"`
	Phone    string      `json:"phone"`
	Country  pgtype.Text `json:"country"`
	City     pgtype.Text `json:"city"`
}

func (q *Queries) UpsertPatientByEmail(ctx context.Context, arg UpsertPatientByEmailParams) (Patient, error) {
	row := q.db.QueryRow(ctx, upsertPatientByEmail,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.City,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
