// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateConsultation(ctx context.Context, arg CreateConsultationParams) (Consultation, error)
	GetPatientByEmail(ctx context.Context, email string) (Patient, error)
	GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error)
	ListActiveTestimonials(ctx context.Context) ([]Testimonial, error)
	ListConsultationsByStatus(ctx context.Context, status string) ([]Consultation, error)
	ListFeaturedTestimonials(ctx context.Context) ([]Testimonial, error)
	UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (Consultation, error)
	UpsertPatientByEmail(ctx context.Context, arg UpsertPatientByEmailParams) (Patient, error)
}

var _ Querier = (*Queries)(nil)
