// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: testimonials.sql

package db

import (
	"context"
)

const listActiveTestimonials = `-- name: ListActiveTestimonials :many
SELECT
    id,
    patient_id,
    treatment_id,
    patient_name,
    rating,
    comment_en,
    patient_flag,
    days_ago,
    consent_given,
    consent_given_at,
    anonymized,
    featured,
    active,
    created_at,
    updated_at
FROM testimonials
WHERE active = TRUE
ORDER BY featured DESC, created_at DESC
`

func (q *Queries) ListActiveTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listActiveTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Testimonial
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.TreatmentID,
			&i.PatientName,
			&i.Rating,
			&i.CommentEn,
			&i.PatientFlag,
			&i.DaysAgo,
			&i.ConsentGiven,
			&i.ConsentGivenAt,
			&i.Anonymized,
			&i.Featured,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedTestimonials = `-- name: ListFeaturedTestimonials :many
SELECT
    id,
    patient_id,
    treatment_id,
    patient_name,
    rating,
    comment_en,
    patient_flag,
    days_ago,
    consent_given,
    consent_given_at,
    anonymized,
    featured,
    active,
    created_at,
    updated_at
FROM testimonials
WHERE active = TRUE
  AND featured = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListFeaturedTestimonials(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listFeaturedTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Testimonial
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.TreatmentID,
			&i.PatientName,
			&i.Rating,
			&i.CommentEn,
			&i.PatientFlag,
			&i.DaysAgo,
			&i.ConsentGiven,
			&i.ConsentGivenAt,
			&i.Anonymized,
			&i.Featured,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
